name: '${name}'
version: '${version}'
main: '${group}.${name}'
api-version: 1.13
load: STARTUP
loadbefore: [ Multiverse-Core, Multiworld ]
author: '${author}'
website: '${website}'
folia-supported: true